# Jenkins doxygen slave image for SCA project.
# TODO: check https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#run
# TODO: add dot and other graphics

#FROM jenkinsci/slave
FROM openjdk:8-jdk
MAINTAINER BTower Labz <labz@btower.net>

ENV HOME /home/jenkins
RUN groupadd -g 10000 jenkins
RUN useradd -c "Jenkins user" -d $HOME -u 10000 -g 10000 -m jenkins
LABEL Description="Provides  which provides the Jenkins agent executable (slave.jar)" Vendor="Jenkins project" Version="3.7"

ARG VERSION=3.7

RUN curl --create-dirs -sSLo /usr/share/jenkins/slave.jar https://repo.jenkins-ci.org/public/org/jenkins-ci/main/remoting/${VERSION}/remoting-${VERSION}.jar \
  && chmod 755 /usr/share/jenkins \
  && chmod 644 /usr/share/jenkins/slave.jar


USER jenkins
RUN mkdir /home/jenkins/.jenkins
VOLUME /home/jenkins/.jenkins
WORKDIR /home/jenkins


COPY jenkins-slave /usr/local/bin/jenkins-slave
COPY jenkins-swarm /usr/local/bin/jenkins-swarm

#Install additional software
USER root
RUN apt-get update && apt-get install -y apt-utils
RUN apt-get update && apt-get install -y curl git unzip lsof nano wget
RUN uname -a
RUN cat /etc/issue

# Install doxygen
RUN apt-get update && apt-get install -y doxygen

USER jenkins
# RUN php --version
RUN mkdir -p /home/jenkins/swarm
RUN cd /home/jenkins/swarm && wget https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/swarm-client/3.4/swarm-client-3.4-javadoc.jar
RUN cd /home/jenkins/swarm && wget https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/swarm-client/3.4/swarm-client-3.4.jar
RUN cd /home/jenkins/swarm && wget https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/swarm-client/3.4/swarm-client-3.4.pom
RUN cd /home/jenkins/swarm && wget https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/swarm-client/3.4/swarm-client-3.4-javadoc.jar.md5
RUN cd /home/jenkins/swarm && wget https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/swarm-client/3.4/swarm-client-3.4-sources.jar.md5
RUN cd /home/jenkins/swarm && wget https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/swarm-client/3.4/swarm-client-3.4.pom.md5

ENTRYPOINT ["jenkins-swarm"]
